import { useEffect, useState } from "react";
import Link from "next/link";
import { apiClient } from "../../services/apiClient";

type User = {id:string;account:string;role:string;status:string;systems:string[]};
const empty:User={id:"",account:"",role:"operator",status:"active",systems:["hospital","shift","school-lunch"]};
export default function CommonUsersPage(){
 const [items,setItems]=useState<User[]>([]); const [editing,setEditing]=useState<User|null>(null); const load=()=>apiClient.get("/portal/users").then(r=>setItems(r.data.items)); useEffect(()=>{load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;const body={account:editing.account,role:editing.role,status:editing.status,systems:editing.systems};if(editing.id)await apiClient.put(`/portal/users/${editing.id}`,body);else await apiClient.post("/portal/users",body);setEditing(null);await load()};
 const toggle=(key:string)=>setEditing(u=>u?{...u,systems:u.systems.includes(key)?u.systems.filter(x=>x!==key):[...u.systems,key]}:u);
 return <main style={{maxWidth:1000,margin:"auto",padding:"40px 24px"}}><Link href="/">← システム選択</Link><h1>共通ユーザー管理</h1><button onClick={()=>setEditing({...empty})}>ユーザーを追加</button>{editing&&<form onSubmit={save} style={{display:"grid",gap:12,margin:"20px 0",padding:20,border:"1px solid #ddd"}}><input type="email" required value={editing.account} onChange={e=>setEditing({...editing,account:e.target.value})}/><select value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})}><option value="operator">一般利用者</option><option value="admin">管理者</option></select><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="active">有効</option><option value="inactive">停止</option></select><label><input type="checkbox" checked={editing.systems.includes("hospital")} onChange={()=>toggle("hospital")}/>病院注文</label><label><input type="checkbox" checked={editing.systems.includes("shift")} onChange={()=>toggle("shift")}/>シフト管理</label><label><input type="checkbox" checked={editing.systems.includes("school-lunch")} onChange={()=>toggle("school-lunch")}/>学校給食</label><div><button type="submit">保存</button><button type="button" onClick={()=>setEditing(null)}>キャンセル</button></div></form>}<div>{items.map(u=><button key={u.id} onClick={()=>setEditing({...u})} style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr 2fr",width:"100%",padding:12,textAlign:"left"}}><span>{u.account}</span><span>{u.role}</span><span>{u.status}</span><span>{u.systems.join(" / ")}</span></button>)}</div></main>
}
